name: flutter_quill_example
description: "Demonstrates how to use the flutter_quill package."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_quill: ^11.0.0-dev.4
  flutter_quill_extensions: ^11.0.0-dev.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_quill_test: ^11.0.0-dev.2
  integration_test:
    sdk: flutter

dependency_overrides:
  flutter_quill:
    path: ../
  flutter_quill_extensions:
    path: ../flutter_quill_extensions
  flutter_quill_test:
    path: ../flutter_quill_test
  quill_native_bridge:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge
  quill_native_bridge_platform_interface:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_platform_interface
  quill_native_bridge_android:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_android
  quill_native_bridge_ios:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_ios
  quill_native_bridge_linux:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_linux
  quill_native_bridge_macos:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_macos
  quill_native_bridge_web:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_web
  quill_native_bridge_windows:
    git:
      url: https://github.com/T-Pro/quill-native-bridge.git
      ref: feature/removeXclip
      path: quill_native_bridge_windows

flutter:
  uses-material-design: true
  assets:
    - assets/images/
